# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def sum_of_even_valued_fibonacci_numbers(up_to)

  sum = 2 # Sum starts at 2 to include the first term, b, that is not added to the sum in the first iteration of the while true loop.
  a = 1
  b = 2
  c = b + a

  while true do

    break if c >= up_to

    if c % 2 == 0
      sum += c
    end

    a = b
    b = c
    c = b + a

  end

  puts "Sum of even valued terms (below #{up_to}}: #{sum}"

end

sum_of_even_valued_fibonacci_numbers(4000000)
